[[glossary]]
[appendix, glossary]
= Glossary

AOP :: Aspect oriented programming

CRUD :: Create, Read, Update, Delete - Basic persistence operations.

DAO :: Data Access Object - Pattern to separate persisting logic from the object to be persisted

Dependency Injection :: Pattern to hand a component's dependency to the component from outside, freeing the component to lookup the dependent itself. For more information, see link:$$https://en.wikipedia.org/wiki/Dependency_Injection$$[https://en.wikipedia.org/wiki/Dependency_Injection].

MyBatis :: MyBatis is a first class persistence framework with support for custom SQL, stored procedures and advanced mappings. MyBatis eliminates almost all of the JDBC code and manual setting of parameters and retrieval of results. MyBatis can use simple XML or Annotations for configuration and map primitives, Map interfaces and Java POJOs (Plain Old Java Objects) to database records. - link:$$https://mybatis.org/mybatis-3/$$[https://mybatis.org/mybatis-3/]

JPA :: Java Persistence API

Spring :: Java application framework - link:$$https://projects.spring.io/spring-framework$$[https://projects.spring.io/spring-framework]
