language: java

jdk:
  - oraclejdk8

env:
  matrix:
    - PROFILE=spring43
    - PROFILE=spring43-next
    - PROFILE=spring5
    - PROFILE=spring5-next

cache:
  directories:
    - $HOME/.m2

sudo: false

install: true

script: "mvn clean dependency:list test -P${PROFILE} -Dsort"
