DROP TABLE IF EXISTS DS_ROLE;
DROP TABLE IF EXISTS DS_USER;
DROP TABLE IF EXISTS DS_GROUP;
DROP TABLE IF EXISTS DEPARTMENT;

CREATE TABLE DS_USER (
  ID            INT IDENTITY,
  FIRSTNAME     VARCHAR(32)  NULL,
  LASTNAME      VARCHAR(32)  NULL,
  AGE           INT          NULL,
  ACTIVE        INT          NULL,
  CREATED_AT    TIMESTAMP    NULL,
  EMAIL_ADDRESS VARCHAR(128) NULL,
  MANAGER_ID    INT          NULL,
  BINARY_DATA   BLOB         NULL,
  DATE_OF_BIRTH DATE         NULL,

  PRIMARY KEY (ID)
);
CREATE TABLE DS_ROLE (
  ID       INT IDENTITY,
  NAME     VARCHAR(32) NULL,
  GROUP_ID INT         NULL,
  PRIMARY KEY (ID)
);
CREATE TABLE DS_GROUP (
  ID   INT IDENTITY,
  NAME VARCHAR(32) NULL,
  CODE VARCHAR(32) NULL,
  PRIMARY KEY (ID)
);
CREATE TABLE DEPARTMENT (
  ID   INT IDENTITY,
  NAME VARCHAR(32) NULL,
  PRIMARY KEY (ID)
);
