CREATE TABLE USER (
  ID            INT(11)     NOT NULL AUTO_INCREMENT,
  FIRSTNAME     VARCHAR(32) NULL,
  LASTNAME      VARCHAR(32) NULL,
  DEPARTMENT_ID INT(11)     NULL,
  AGE           INT(3)      NULL,
  PRIMARY KEY (ID)
);
CREATE TABLE ROLE (
  ID   INT(11)     NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(32) NULL,
  PRIMARY KEY (ID)
);
CREATE TABLE DEPARTMENT (
  ID   INT(11)     NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(32) NULL,
  PRIMARY KEY (ID)
);